# Generated by Django 4.0.6 on 2022-08-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupUsers',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(default='Коллега', max_length=50)),
                ('user_role', models.CharField(choices=[('ORG', 'Organizer'), ('SPK', 'Speaker'), ('USR', 'Visitor')], default='USR', max_length=3)),
            ],
        ),
    ]
