# Generated by Django 3.2.13 on 2022-08-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_db', '0002_alter_guest_telegram_id_alter_speaker_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
    ]
