# Generated by Django 4.0.6 on 2022-08-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_db', '0002_meetupusers_user_surname_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetupusers',
            name='user_role',
            field=models.CharField(choices=[('SPK', 'Speaker'), ('ORG', 'Organizer'), ('USR', 'Visitor')], default='USR', max_length=3),
        ),
    ]
