# Generated by Django 4.0.6 on 2022-08-06 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_db', '0003_alter_guest_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='guest', to='meetup_db.guest', verbose_name='ID гостя')),
                ('speaker_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='speaker', to='meetup_db.speaker', verbose_name='ID спикера')),
            ],
        ),
    ]
