# Generated by Django 4.0.6 on 2022-08-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_db', '0004_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetupusers',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='meetupusers',
            name='user_role',
            field=models.CharField(choices=[('USR', 'Visitor'), ('SPK', 'Speaker'), ('ORG', 'Organizer')], default='USR', max_length=3),
        ),
    ]
