# Generated by Django 4.0.6 on 2022-08-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_db', '0004_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='guest_id',
            new_name='guest',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='speaker_id',
            new_name='speaker',
        ),
    ]
