# Generated by Django 4.0.6 on 2022-08-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_db', '0006_alter_meetupusers_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetupusers',
            old_name='user_id',
            new_name='telegram_id',
        ),
        migrations.AlterField(
            model_name='meetupusers',
            name='user_name',
            field=models.CharField(blank=True, default='Коллега', max_length=50),
        ),
        migrations.AlterField(
            model_name='meetupusers',
            name='user_role',
            field=models.CharField(choices=[('SPK', 'Speaker'), ('ORG', 'Organizer'), ('VST', 'Visitor')], default='VST', max_length=3),
        ),
        migrations.AlterField(
            model_name='meetupusers',
            name='user_surname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
