# Generated by Django 4.0.6 on 2022-08-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_db', '0007_rename_user_id_meetupusers_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetupusers',
            name='user_role',
            field=models.CharField(choices=[('ORG', 'Organizer'), ('SPK', 'Speaker'), ('VST', 'Visitor')], default='VST', max_length=3),
        ),
    ]
