# Generated by Django 4.0.6 on 2022-08-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_db', '0008_alter_meetupusers_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetupusers',
            name='user_name',
            field=models.CharField(default='Коллега', max_length=50),
        ),
        migrations.AlterField(
            model_name='meetupusers',
            name='user_role',
            field=models.CharField(choices=[('SPK', 'Speaker'), ('ORG', 'Organizer'), ('VST', 'Visitor')], default='VST', max_length=3),
        ),
    ]
